# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - ZadTopBlob

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build Modules and Populate Portal/Bin
        shell: powershell
        run: .\build_and_publish.ps1

      - name: Prepare Publish Directory
        shell: cmd
        run: |
          mkdir published
          robocopy Portal published /E /XD .svn .git obj bin\Debug bin\Release
          if %ERRORLEVEL% LEQ 8 exit 0
          exit 1

      - name: Verify Publish Content
        shell: cmd
        run: dir published

      - name: Zip Publish Directory
        shell: powershell
        run: Compress-Archive -Path published\* -DestinationPath site.zip -Force

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ZadTopBlob
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: site.zip